name: Deploy To Staging

on:
 workflow_dispatch:
   inputs:
     module:
       description: 'Module'
       required: true
       type: choice
       options:
         - report
         - account
         - project
     version:
       description: 'Version Name'
       required: true
       type: string


jobs:

  deploy_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant permission for gradle wrapper to execute
        run: chmod +x gradlew

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project with gradle
        run: ./gradlew clean build --quiet
        env:
          packageToken: ${{ secrets.PACKAGES_TOKEN }}

      - name: Set Up Cloud SDK For Staging
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '363.0.0'
          project_id: ${{ secrets.STAG_PROJECT_ID }}
          service_account_key: ${{ secrets.STAG_GCLOUD_SA_CREDENTIAL }}
          export_default_credentials: true

      - name: Deploy Staging
        run: |
          cd report
          ../gradlew appenginedeploy -Dname=staging-goclockin-dashboard
