package com.yoco.commons.enums;

public enum EmailKeys {
    ACTION,ADJUSTMENTS_DELETED_CONTENT,ADMIN_MAIL,ADMIN_NAME,COMPANY_NAME,CURRENT_YEAR,DOMAIN_IMAGE,FAILED_COUNT_WITH_MSG,
    LOGIN_MAIL,REDIRECT_URL,START_DATE,SUCCESS_COUNT,SUPPORT_MAIL,TOTAL_COUNT,USER_NAME,
    MESSAGE,IN_DATE,IN_TIME,OUT_TIME,DURATION,DURATION_DIFF,SESSION_DETAILS,TOTAL_HOURS
}
